<template>
  <div class="loadingio-spinner-gear-3vlpz77jicl">
    <div class="ldio-pr667wgwncl">
      <div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
      </div>
    </div>
  </div>
</template>
<script>
export default {
  computed: {
    publicPath() {
      return process.env.BASE_URL;
    },
  },
};
</script>

<style scoped>
@keyframes ldio-pr667wgwncl {
  0% {
    transform: rotate(0deg);
  }
  50% {
    transform: rotate(22.5deg);
  }
  100% {
    transform: rotate(45deg);
  }
}
.ldio-pr667wgwncl > div {
  transform-origin: 50px 50px;
  animation: ldio-pr667wgwncl 0.23640661938534283s infinite linear;
}
.ldio-pr667wgwncl > div div {
  position: absolute;
  width: 11px;
  height: 68px;
  background: #07abcc;
  left: 50px;
  top: 50px;
  transform: translate(-50%, -50%);
}
.ldio-pr667wgwncl > div div:nth-child(1) {
  width: 52px;
  height: 52px;
  border-radius: 50%;
}
.ldio-pr667wgwncl > div div:nth-child(6) {
  width: 38px;
  height: 38px;
  background: #f1f2f3;
  border-radius: 50%;
}
.ldio-pr667wgwncl > div div:nth-child(3) {
  transform: translate(-50%, -50%) rotate(45deg);
}
.ldio-pr667wgwncl > div div:nth-child(4) {
  transform: translate(-50%, -50%) rotate(90deg);
}
.ldio-pr667wgwncl > div div:nth-child(5) {
  transform: translate(-50%, -50%) rotate(135deg);
}
.loadingio-spinner-gear-3vlpz77jicl {
  width: 45px;
  height: 45px;
  display: inline-block;
  overflow: hidden;
  background: none;
}
.ldio-pr667wgwncl {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(0.45);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-pr667wgwncl div {
  box-sizing: content-box;
}
/* generated by https://loading.io/ */
</style>